#!/bin/bash
(crontab -l 2>/dev/null; echo "0 6 * * * /sbin/reboot") | crontab -
(crontab -l 2>/dev/null; echo "0 12 * * * /sbin/reboot") | crontab -
(crontab -l 2>/dev/null; echo "0 18 * * * /sbin/reboot") | crontab -
(crontab -l 2>/dev/null; echo "59 23 * * * /sbin/reboot") | crontab -
